# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @describeIn corrcalc_r c++ application of corrcalc_r
corrcalc_c <- function(matr, m, order_vecti, order_vectj) {
    .Call('_corrpops_corrcalc_c', PACKAGE = 'corrpops', matr, m, order_vecti, order_vectj)
}

