# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the Covariance Matrix of a Vectorized Correlation matrix
#'
#' For inner use.
#'
#' @name corrcalc_c
#'
#' @seealso \link[corrfuncs]{corrmat_covariance} \link[corrfuncs]{triangle2vector}
NULL

corrcalc_c <- function(matr, m, order_vecti, order_vectj) {
    .Call('_corrfuncs_corrcalc_c', PACKAGE = 'corrfuncs', matr, m, order_vecti, order_vectj)
}

