# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corrcalc_c <- function(matr, m, order_vecti, order_vectj) {
    .Call('_corrfuncs_corrcalc_c', PACKAGE = 'corrfuncs', matr, m, order_vecti, order_vectj)
}

